"""
Curio agent — daily personal content digest orchestrator.

Modes:
- daily          : fetch, filter, rank, summarize, write, deliver
- sunday-review  : daily + weekly review section + taste.yaml.proposed diff
- dry-run        : same as daily but no email actually sent

Uses claude_agent_sdk; LLM auth is auto-picked from the environment.
"""

import argparse
import asyncio
import logging
import os
import sys
from datetime import datetime

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
    TextBlock,
    ToolUseBlock,
)

from curio import config
from curio.mcp_servers.curio_tools import create_curio_mcp_server

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


# ============================================================================
# PROMPTS
# ============================================================================

DAILY_PROMPT = """You are Curio — the user's personal daily content agent.

Today is {date} ({weekday}). The rotating deep-dive topic for {weekday} is: **{rotation_topic}**.

Assemble today's ~15-minute digest by fetching candidates, filtering to what the user cares about, respecting structural diversity, writing summaries, and delivering the edition.

## Process

1. `read_taste_config` — load interests, anti-interests, calibration examples, novelty settings. This is your affinity model; refer back to it constantly.

2. Fetch candidates:
   - `fetch_quote_of_the_day()` — a curated daily quote for the epigraph at the top of the edition
   - `fetch_hackernews(count=15)`
   - `fetch_arxiv(categories=<pick from the user's interests>, days_back=2, count=15)`
   - `fetch_wikipedia_otd()`
   - `fetch_comic(source=<rotate through xkcd/smbc/oatmeal>)`
   - `WebSearch` for news — run 2-3 searches shaped by interests (e.g. "top world news today", "top tech news today", "{rotation_topic} news today"). Do NOT search for anything in anti-interests.
   - `WebSearch` for A* venue papers when the deep-dive topic warrants it — e.g. "recent OSDI 2026 papers", "SOSP 2026 accepted papers", "VLDB 2026 best paper". Arxiv covers most systems/AI research directly; use WebSearch as the venue-specific complement.

3. `compute_novelty(candidates)` on the full pool to get novelty scores vs the last 7 days.

4. Decide include/exclude per candidate with a one-line reason. Use:
   - Interest weights (higher = more affinity)
   - Anti-interests → hard exclude
   - Calibration examples (include_like / exclude_like) as few-shot guidance
   - Novelty (heavily penalize duplicates of recent editions)

5. Apply structural constraints (from sources.yaml):
   - Slots: news×4, HN×3, paper×1, deep-dive×1, fact×1, comic×1
   - Per-source cap: max 2 items from the same source
   - Per-topic cap: no single topic > ~30% of items
   - Exploration: reserve ~20% of remaining slots for items from your LOWEST-scoring interest categories today (prevents filter-bubble collapse)

6. For each chosen item write a concise summary — 60-100 words normally, 120-150 for paper-of-the-day and deep-dive. Always include the URL and one sentence on "why this matters to the user."

7. Assemble the edition markdown. **Item format is important — follow it exactly:**

```
# Curio · {date} · {weekday}

> "The quote text goes here, verbatim from fetch_quote_of_the_day."
> — Author Name

_A ~15 minute read._

## World & Tech News

**[Headline as a markdown link](https://url)** — 2-3 sentence body describing the item. **Why it matters:** one crisp sentence.

**[Second headline](https://url)** — body. **Why it matters:** …

## Hacker News

**[HN title](https://the-linked-article-url)** — body ([discussion](https://news.ycombinator.com/item?id=X)). **Why it matters:** …

## Paper of the Day

**[Paper title](https://arxiv.org/abs/…)** — 120-150 word summary, author names inline if notable. **Why it matters:** …

## Deep Dive: {rotation_topic}

**[Item title](https://url)** — 120-150 word deep-dive summary. **Why it matters:** …

## Fact of the Day

One or two sentences tied to today's date, with a [source link](https://url).

## Comic

**[Comic title](https://comic-page-url)** — source: xkcd/smbc/oatmeal.

![alt text](https://image-url)

---
_Generated by Curio._
```

**Formatting rules:**
- Titles are always `**[text](url)**` — bold markdown links on one line. NEVER use `###` for item titles, and NEVER put a bare URL on its own line.
- Body prose flows immediately after the em-dash `—`. Keep it in a single paragraph per item.
- "**Why it matters:** …" is a bold-inline continuation of that same paragraph, not a separate line.
- Comic image uses `![alt](url)` so it renders inline in the email.

8. `write_edition(date, weekday, markdown, metadata={items, categories, sources}, rotation_topic)` — the tool also renders a companion styled HTML file next to the markdown.

9. `write_log(date, entries=[{title, url, source, included, category, reason}, ...])` — every candidate + your decision + one-line reason.

10. `send_email(subject, markdown_body, date, weekday, rotation_topic)` — subject like "curio · {date} · {weekday}". Pass the same markdown you wrote to the edition file; Python wraps it in a styled HTML email template.

## Rules

- Quality over quantity. A tight digest of 8 strong items beats a padded one of 15 mediocre.
- Reasoning transparency: every include/exclude decision goes into the log.
- Novelty is not a suggestion: skip items ≥85% similar to something in the last 7 days unless there's genuinely new info.
- Diversity is a hard constraint: respect per-source and per-topic caps even if it means dropping favorites.
- No hype: skip funding announcements, product-launch fluff, celebrity/gossip, crypto pumps.
- Write like a smart friend: crisp, no jargon-for-its-own-sake, always end with one sentence on why it matters.
"""


SUNDAY_REVIEW_APPENDIX = """

## Sunday extra: weekly review

After the normal edition steps, ALSO do:

11. `read_recent_editions(days=7)` to load the past week.

12. Analyze the week:
    - Which categories dominated? Which were under-represented?
    - Which included items now look like noise in retrospect?
    - Are the anti-interests catching what they should?
    - Any patterns in almost-included items (score 0.4–0.6) that suggest a calibration edit?

13. Propose 2-3 concrete edits to taste.yaml. For each:
    - What to change (add keyword, add calibration example, adjust weight, add anti-interest)
    - Why (evidence from the week's logs)

14. Add a `## Weekly Review` section at the end of today's edition markdown (before calling `write_edition`) containing the proposals.
"""

SUNDAY_REVIEW_PROMPT = DAILY_PROMPT + SUNDAY_REVIEW_APPENDIX


# ============================================================================
# AGENT RUNNER
# ============================================================================

async def run_agent(mode: str, date_override: str | None = None) -> str:
    settings = config.load_settings()
    sources = config.load_sources()
    agent_settings = settings["agent"]

    today = (
        datetime.strptime(date_override, "%Y-%m-%d")
        if date_override
        else datetime.now()
    )
    weekday_name = today.strftime("%A")
    weekday_idx = today.weekday()
    rotation_topic = sources["weekday_rotation"].get(weekday_idx, "wildcard")

    prompt_template = (
        SUNDAY_REVIEW_PROMPT if mode == "sunday-review" else DAILY_PROMPT
    )
    # Use .replace() rather than .format() — the prompt contains literal
    # code-like braces (e.g. `metadata={items, categories, sources}`) that
    # would otherwise be misinterpreted as format placeholders.
    prompt = (
        prompt_template.replace("{date}", today.strftime("%Y-%m-%d"))
        .replace("{weekday}", weekday_name)
        .replace("{rotation_topic}", rotation_topic)
    )

    curio_server = create_curio_mcp_server()
    server_name = "curio"

    allowed_tools = [
        f"mcp__{server_name}__read_taste_config",
        f"mcp__{server_name}__read_recent_editions",
        f"mcp__{server_name}__fetch_hackernews",
        f"mcp__{server_name}__fetch_arxiv",
        f"mcp__{server_name}__fetch_quote_of_the_day",
        f"mcp__{server_name}__fetch_wikipedia_otd",
        f"mcp__{server_name}__fetch_comic",
        f"mcp__{server_name}__compute_novelty",
        f"mcp__{server_name}__write_edition",
        f"mcp__{server_name}__write_log",
        f"mcp__{server_name}__send_email",
        "WebSearch",
    ]
    # dry-run mode is enforced by the tool itself (CURIO_DRY_RUN=1) rather
    # than by omitting it from allowed_tools — this way the agent still
    # completes the full flow and reports what would have been sent.
    if mode == "dry-run":
        os.environ["CURIO_DRY_RUN"] = "1"
    else:
        os.environ.pop("CURIO_DRY_RUN", None)

    system_prompt = (
        f"You are Curio, a personal daily content digest agent.\n"
        f"Mode: {mode.upper()}\n"
        f"Date: {today.strftime('%Y-%m-%d')} ({weekday_name})\n"
        f"Rotation topic: {rotation_topic}\n"
    )

    max_turns = (
        agent_settings["max_turns_sunday"]
        if mode == "sunday-review"
        else agent_settings["max_turns_daily"]
    )

    options = ClaudeAgentOptions(
        mcp_servers={server_name: curio_server},
        allowed_tools=allowed_tools,
        system_prompt=system_prompt,
        permission_mode=agent_settings["permission_mode"],
        max_turns=max_turns,
    )

    final_response = ""
    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(prompt)
            async for message in client.receive_response():
                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock):
                            print(block.text)
                            final_response += block.text + "\n"
                        elif isinstance(block, ToolUseBlock):
                            logger.info(f"Tool: {block.name}")
                elif isinstance(message, ResultMessage):
                    if message.is_error:
                        logger.error(f"Agent error: {message.result}")
                    duration = message.duration_ms
                    cost = message.total_cost_usd or 0
                    logger.info(
                        f"Agent completed in {duration}ms, cost: ${cost:.4f}"
                    )
    except Exception as e:
        logger.error(f"Agent error: {e}")
        raise

    return final_response


# ============================================================================
# CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description="Curio daily content digest agent")
    parser.add_argument(
        "--mode",
        choices=["daily", "sunday-review", "dry-run"],
        default="dry-run",
        help="Run mode (default: dry-run — no email actually sent)",
    )
    parser.add_argument(
        "--date",
        default=None,
        help="Override date as YYYY-MM-DD (default: today)",
    )
    args = parser.parse_args()

    print(f"Running Curio — mode: {args.mode.upper()}")

    try:
        asyncio.run(run_agent(mode=args.mode, date_override=args.date))
    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(0)
    except Exception as e:
        logger.error(f"Agent failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
